version: '3' # Docker-compose yml version for docker compose builder
services:
  web:
   build: ./spring-music/
   depends_on:
     - db_mysql
   ports:
     - 8080:8080
   restart: always
   networks: # Define netwroks per service / role
     - app_layer
  db_mysql:
    image: wangxian/alpine-mysql
    environment: # env variables
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music
    ports:
      - 3302:3306
    networks:
      - db_layer
networks: # custome configuration per network defined
 db_layer:
  driver: bridge
 app_layer:
  driver: bridge
